// Mocks generated by Mockito 5.4.6 from annotations
// in btg_capital/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:btg_capital/features/funds/data/datasources/funds_local_datasource.dart'
    as _i7;
import 'package:btg_capital/features/funds/data/models/fund_model.dart' as _i8;
import 'package:btg_capital/features/funds/domain/entities/fund_entity.dart'
    as _i4;
import 'package:btg_capital/features/funds/domain/entities/portfolio_entry_entity.dart'
    as _i6;
import 'package:btg_capital/features/funds/domain/entities/transaction_entity.dart'
    as _i5;
import 'package:btg_capital/features/funds/domain/repositories/funds_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FundsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundsRepository extends _i1.Mock implements _i2.FundsRepository {
  MockFundsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FundEntity>> getFunds() =>
      (super.noSuchMethod(
            Invocation.method(#getFunds, []),
            returnValue: _i3.Future<List<_i4.FundEntity>>.value(
              <_i4.FundEntity>[],
            ),
          )
          as _i3.Future<List<_i4.FundEntity>>);

  @override
  _i3.Future<void> subscribeToFund({
    required _i4.FundEntity? fund,
    required int? amount,
    required _i5.NotificationMethodEnum? notificationMethod,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToFund, [], {
              #fund: fund,
              #amount: amount,
              #notificationMethod: notificationMethod,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelFundSubscription({required int? fundId}) =>
      (super.noSuchMethod(
            Invocation.method(#cancelFundSubscription, [], {#fundId: fundId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i5.TransactionEntity> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: <_i5.TransactionEntity>[],
          )
          as List<_i5.TransactionEntity>);

  @override
  List<_i6.PortfolioEntryEntity> getPortfolio() =>
      (super.noSuchMethod(
            Invocation.method(#getPortfolio, []),
            returnValue: <_i6.PortfolioEntryEntity>[],
          )
          as List<_i6.PortfolioEntryEntity>);

  @override
  int getBalance() =>
      (super.noSuchMethod(Invocation.method(#getBalance, []), returnValue: 0)
          as int);
}

/// A class which mocks [FundsLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFundsLocalDatasource extends _i1.Mock
    implements _i7.FundsLocalDatasource {
  MockFundsLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.FundModel>> getFunds() =>
      (super.noSuchMethod(
            Invocation.method(#getFunds, []),
            returnValue: _i3.Future<List<_i8.FundModel>>.value(
              <_i8.FundModel>[],
            ),
          )
          as _i3.Future<List<_i8.FundModel>>);
}
